services:

  app:
    build: .
    container_name: app_go
    tty: true
    stdin_open: true
    environment:
      - CGO_ENABLED=0
    env_file:
      - 'prod.env'
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"

  db:
    image: postgres:16-alpine3.22
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=prefeito
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=prefeitura
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8000:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  redis:
    image: redis:8.4.2-alpine3.22
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redis_insight
    ports:
      - "5540:5540"
    restart: always
    depends_on:
      - redis

volumes:
  postgres_data:
  redis_data:
  pgadmin_data: